name: phidata-agent-app
services:
- name: web
  git:
    branch: main
    repo_clone_url: https://github.com/therealmakervn/my-phidata-app.git
    build_command: pip install -r requirements.txt
  run_command: uvicorn api.main:app --host 0.0.0.0 --port $PORT
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
    - path: /
  health_check:
    http_path: /health
databases:
  - name: db
    engine: PG
    version: "12"
