name: phidata-agent-app
services:
- name: web
  git:
    branch: main
    repo_clone_url: https://github.com/therealmakervn/my-phidata-app.git
    build_command: pip install -r requirements.txt
  envs:
    - key: PYTHONPATH
      value: /workspace
  run_command: python -m uvicorn api.main:app --host 0.0.0.0 --port $PORT
  environment_slug: python
databases:
  - name: db
    engine: PG
    version: "12"
